#!/bin/bash

#主机
#ip="192.168.0.18"
#password="88164657"
#user="root"
#password="xhrt123"
#user="xhrt"


#阿里云
#ip="61.174.8.254"
#user="ubuntu"
#password="GZyunzhishuju123"

#阿里云
#ip="192.168.0.17"
#user="root"
#password="88164657"

#阿里云
ip="139.129.99.185"
user="root"
password="88164657XHrt"
remote_path="/usr/local/nginx/html/yxjqd/"
function p2p_enter()
{
	expect -c "
		spawn ssh $user@$ip;
		expect {
			\"*password:\" {send \"$password\r\"; exp_continue}
            \"*#\" {send \" cd  ${remote_path}\rPS1=\'\\\u@\\\w\\\n$\'\r\"}
		}
		interact
	"
}


_localfile=$1
function p2p_sendfile()
{
    [ -z "$_localfile" ]&&return
    expect -c "
        spawn scp "${_localfile}" root@$ip:${remote_path}${_localfile}
        expect {
            \"*password:\" {send \"$password\r\"}
        }
        interact
    "
}
if [ -z "$1" ];then
    p2p_enter
else
    p2p_sendfile
fi
